### ISSUE TITLE
Restart the download from the package in which they stayed.

### ISSUE THREAD

**Issue by juanuni** [scottkosty/install-tl-ubuntu#26]
For several days I have problems with the internet. The internet goes time to time and downloading packets is interrupted. The most frustrating thing is that the download starts again from scratch. There would be some form of texlive-tl-ubuntu to restart the download from where the download was interrupted? Sorry for my English.

**Comment by scottkosty** [comment]
I believe the subsequent attempts to install do use the previous attempts. It does not appear that way because the package list starts from 0, but you should see that it gets up to the point where it left off quicker than the first time. I don't know of any way to improve this with the TeX Live installer. If you do, please let me know.

Another idea for you is that you might consider downloading the .iso and installing from that.  It is large, but there is a torrent for it. And it is worth it if you will make several installations of TeX Live. You can use the .iso as follows:

    install-tl-ubuntu --iso <ISO FILE>

See the help for more information.

**Comment by juanuni** [comment]
Thanks for your response. I am not an expert user but I installed (that I think) TeXLive following https://www.tug.org/texlive/acquire-mirror.html  and  https://www.tug.org/texlive/quickinstall.html (with any difference to run the install-tl script).

However, I have a problem. When I run pdflatex in the terminal it appears as not installed.

I have searched for information on completing the installation, but it has not caused any effect. Still ongoing with the problem

I'm looking for some TeXLive forum where I can find help. If you know somewhere where I can find help, I would appreciate you. I told you.

**Comment by scottkosty** [comment]
I suggest following the instructions here:
http://tex.stackexchange.com/questions/1092/how-to-install-vanilla-texlive-on-debian-or-ubuntu

In fact, install-tl-ubuntu was originally based on that answer and was meant to easily automate them.

latex-community.org is a good and friendly forum that might be helpful.

Since I don't think there's anything I can do in install-tl-ubuntu to resolve this issue, I will close it. Best of luck!
